on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [14, 16]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
           node-version: ${{ matrix.version }}
      - name: installing dependencies
        run: npm i
      - name: run unit test
        run: npm test

          
