on:
  push:
    branches:
      - 'master'

jobs:
  website-test:
    name: 'unit Test'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
      - name: installing dependencies
        run: npm i
      - name: running unit test
        run: npm test

  deploy:
    name: 'Deploy Website with cdk to aws stack 🚀'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    needs: [website-test]
    steps:
      - uses: actions/checkout@master
      - name: installing website dependencies
        run: npm i
      - name: build website
        env:
          VITE_GRAPHQL_ENDPOINT: ${{ secrets.VITE_GRAPHQL_ENDPOINT }}
          VITE_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.VITE_GITHUB_PERSONAL_ACCESS_TOKEN }}
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploying website and infrastructure
        working-directory: ./infrastructure
        run: npx sst deploy --stage prod

  # lighthouse:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: curl health endpoint
  #       run: |
  #         curl -X GET https://hufghani.dev
  #     - name: Audit URLs using Lighthouse
  #       uses: treosh/lighthouse-ci-action@v8
  #       with:
  #         urls: |
  #           https://hufghani.dev
  #           https://hufghani.dev/project
  #         budgetPath: ./.github/lighthouse/budget.json # test performance budgets
  #         uploadArtifacts: true # save results as an action artifacts
  #         temporaryPublicStorage: true # upload lighthouse report to the temporary storage
