on:
  push:
    branches:
      - 'master'

jobs:
  website-test:
    name: 'unit Test'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@latest
        with:
          node-version: 22
          cache: 'npm'
      - name: installing dependencies
        run: npm i
      - name: running unit test
        run: npm test

  deploy:
    env:
      VITE_GRAPHQL_ENDPOINT: ${{ secrets.VITE_GRAPHQL_ENDPOINT }}
      VITE_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.VITE_GITHUB_PERSONAL_ACCESS_TOKEN }}
    name: 'Deploy Website with cdk to aws stack 🚀'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    needs: [website-test]
    steps:
      - uses: actions/checkout@master
      - name: installing website dependencies
        run: npm i
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@latest
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploying website and infrastructure
        run: npm run build && cd ./build && npx cdk deploy --require-approval never

  unlighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/setup-node@latest
      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer
      - name: Unlighthouse assertions and client
        run:
          unlighthouse-ci --site https://hufghani.dev --budget 95 --build-static --reporter
          jsonExpanded
