on:
  pull_request:
    branches:
      - 'master'

jobs:
  website-test:
    env:
      VITE_GRAPHQL_ENDPOINT: ${{ secrets.VITE_GRAPHQL_ENDPOINT }}
      VITE_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.VITE_GITHUB_PERSONAL_ACCESS_TOKEN }}
    name: 'unit Test'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
      - name: installing dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: running test
        run: npm run test
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: playwright-report/
